### PR TITLE
fix: WACI share shows missing credential page before sharing credential

### LINKED ISSUE #1608: WACI share shows missing credential page for brief second before showing main state
https://user-images.githubusercontent.com/33902374/159726239-7a608353-dca7-496f-8af4-5d703d599262.mov

### PR DESCRIPTION
**Pull request by talwinder50**
closes #1608

Signed-off-by: talwinder50 <talwinderkaur50@gmail.com>

https://user-images.githubusercontent.com/7862595/160029319-bb182391-af4e-41a1-ac7a-26e7675006a1.mov

https://user-images.githubusercontent.com/7862595/160029408-d8e72e51-fd60-4eaf-b5fe-4468aae3c96a.mov

### CODE REVIEW

**Review by victro — APPROVED** [review]

File: cmd/wallet-web/src/pages/OIDCShare.vue [hunk 1]
```diff
@@ -237,7 +235,8 @@ export default {
       if (!e.message.includes('12009')) {
         this.errors.push('Error initiating credential share');
       }
-      console.error('initiating credential share failed,', e);
```
Comment (birtony) [inline cmd/wallet-web/src/pages/OIDCShare.vue:240]: I think we should keep this for debugging purposes since we don't log this error anywhere else

File: cmd/wallet-web/src/pages/WACIShare.vue [hunk 2]
```diff
@@ -243,7 +241,8 @@ export default {
       if (!e.message.includes('12009')) {
         this.errors.push('Error initiating credential share');
       }
-      console.error('initiating credential share failed,', e);
```
Comment (birtony) [inline cmd/wallet-web/src/pages/WACIShare.vue:246]: I think we should keep this for debugging purposes since we don't log this error anywhere else

File: cmd/wallet-web/src/pages/OIDCShare.vue (hunk 1 above)
Comment (talwinder50) [reply cmd/wallet-web/src/pages/OIDCShare.vue:240]: updated

Comment (birtony) [reply cmd/wallet-web/src/pages/OIDCShare.vue:240]: Can we keep the console.error on the same line as before?

**Review by birtony — APPROVED** [review]
