### PR TITLE
fix: redirect user to correct page upon signin

### LINKED ISSUE #1810: Redirect user to correct specific page upon sign in
If the user who is not yet signed in tries to go to the credentials page (i.e. https://wallet.stg.trustbloc.dev/credentials), they will get redirected to the login page, and once they log in, then they will get redirected to the vaults page (https://wallet.stg.trustbloc.dev/vaults) instead of the credentials page. 
The user should get redirected back to the original URL they were trying to get to.

### PR DESCRIPTION
**Pull request by HeidiHan0000**
Closes #1810 
Redirect to Credentials page:

https://user-images.githubusercontent.com/44453261/185851525-03671ea7-6884-4345-a45b-b5205abc8e83.mov

Redirect to WACI page after sign in in the WACI issuance flow:

https://user-images.githubusercontent.com/44453261/185923006-bdafc201-52d7-464f-82ed-d7449af16a1c.mov

Signed-off-by: heidihan0000 <daeun.han@avast.com>

### CODE REVIEW

File: cmd/wallet-web/src/store/modules/user.js [hunk 1]
```diff
@@ -244,6 +259,9 @@ export default {
     getGnapReqAccessResp(state) {
       return state.gnapRequestAccessResp;
     },
+    getPageName(state) {
+      return state.pageName;
```
Comment (birtony) [inline cmd/wallet-web/src/store/modules/user.js:263]: Can we `JSON.parse()` here instead?

**Review by talwinder50 — APPROVED** [review]

File: cmd/wallet-web/src/store/modules/user.js (hunk 1 above)
Comment (HeidiHan0000) [reply cmd/wallet-web/src/store/modules/user.js]: Yep, changed!

**Review by sudeshrshetty — APPROVED** [review]
