### PR TITLE
fix: Added spinner as loading state for user authentication 

### LINKED ISSUE #1809: Show loading state while finishing user authentication
image

### PR DESCRIPTION
**Pull request by HeidiHan0000**
Related to #1809 
Added the Spinner icon to indicate to user that the wallet is loading while finishing user authentication. 
This was added as a temporary fix; in the future, the loading state should be the skeleton loaders for the corresponding page. 
Signed-off-by: heidihan0000 <daeun.han@avast.com>

https://user-images.githubusercontent.com/44453261/180890467-3c834808-9927-44da-8038-708ed41b7a58.mov

### CODE REVIEW

**Review by rolsonquadras — APPROVED** [review]
Thanks for the quick workaround 👍

File: cmd/wallet-web/src/router/index.js [hunk 1]
```diff
@@ -60,6 +60,7 @@ router.beforeEach(async (to, from) => {
         // later on, if we need to authenticate the same user again we just call requestAccess
         // if needed, it will return us a new continue access token to complete user authentication
         store.dispatch('updateGnapReqAccessResp', null);
+        store.dispatch('updateUserLoaded', true);
```
Comment (birtony) [inline cmd/wallet-web/src/router/index.js:63]: @HeidiHan0000, you also need to dispatch in the end of every other guard, otherwise user won't be able to get past the loading spinner when signing back in, etc.

**Comment by HeidiHan0000** [comment]
Recordings:
Sign up + signout:

https://user-images.githubusercontent.com/44453261/181064473-f8d23da8-ac12-4d55-8296-02fd9d7d37e6.mov

Sign in + sign out:

https://user-images.githubusercontent.com/44453261/181064557-d90dff4f-fbcc-428f-a77d-916586dd5701.mov

Refresh:

https://user-images.githubusercontent.com/44453261/181064618-559adb51-9e51-41c1-a392-e23fdfee610a.mov

Open from new tab:

https://user-images.githubusercontent.com/44453261/181064657-4ee73e72-e6a5-42f8-8cf8-f33bbade1ef3.mov

From OIDC issuance:

https://user-images.githubusercontent.com/44453261/181065166-6a6fbe05-11a3-49a8-be8d-f9c70a8598ae.mov

**Review by birtony — APPROVED** [review]
Perfect!
