### PR TITLE
fix: Fix the selected default in the dropdown to save cred in default cred

### LINKED ISSUE #1253: Fix the selected default in the dropdown to save cred in default cred
Presently you have to click the dropdown to default vault to save the credential

### PR DESCRIPTION
**Pull request by talwinder50**
closes #1253

Signed-off-by: talwinder50 <talwinderkaur50@gmail.com>

### CODE REVIEW

**Review by fqutishat — APPROVED** [review]

**Review by birtony — CHANGES_REQUESTED** [review]

File: cmd/wallet-web/src/pages/Store.vue [hunk 1]
```diff
@@ -248,6 +247,10 @@ export default {
     fetchAllVaults: async function (token, collectionManager) {
       const { contents } = await collectionManager.getAll(token);
       this.vaults = Object.values(contents).map((vault) => vault);
+      // Default vault is selected vault by default, it is created on vault setup and must be only one.
+      const defaultVault = this.vaults.filter((vault) => vault.name.includes('Default'));
+      const fetchedDefaultId = defaultVault.map((value) => value.id);
+      this.selectedVault = fetchedDefaultId.values().next().value;
```
[the remark this answers is not in the document]
Comment (birtony) [reply cmd/wallet-web/src/pages/Store.vue:253]: In addition, since you already have a method to set `this.selectedVault`, you should use it here as well instead of duplicating your code:
```js
this.setSelectedVault(defaultVaultId);
```

File: cmd/wallet-web/src/pages/Store.vue [hunk 2]
```diff
@@ -158,7 +158,7 @@ export default {
       processedCredentials: [],
       errors: [],
       vaults: [],
-      selectedVault: '',
+      setSelectedVault: '',
```
Comment (birtony) [inline cmd/wallet-web/src/pages/Store.vue:161]: Why did you rename your data variable instead of a method? This should stay as it used to be - `selectedVault`, it is not a function

File: cmd/wallet-web/src/pages/Store.vue [hunk 3]
```diff
@@ -225,7 +224,7 @@ export default {
         });
     },
     vaultSelected: function (e) {
```
Comment (birtony) [inline cmd/wallet-web/src/pages/Store.vue:226]: This method should be called `setSelectedVault`, because what does is set `this.selectedVault`

File: cmd/wallet-web/src/pages/Store.vue [hunk 4]
```diff
@@ -248,6 +247,8 @@ export default {
     fetchAllVaults: async function (token, collectionManager) {
       const { contents } = await collectionManager.getAll(token);
       this.vaults = Object.values(contents).map((vault) => vault);
+      // Default vault is selected vault by default, it is created on vault setup and must be only one.
+      this.setSelectedVault = this.vaults.find((vault) => vault.name === 'Default Vault').id;
```
Comment (birtony) [inline cmd/wallet-web/src/pages/Store.vue:251]: You didn't reuse the `setSelectedVault` method to update `this.selectedVault`

**Review by birtony — CHANGES_REQUESTED** [review]

File: cmd/wallet-web/src/pages/Store.vue (hunk 2 above)
Comment (talwinder50) [reply cmd/wallet-web/src/pages/Store.vue]: shoot i misread your comment , updated now

File: cmd/wallet-web/src/pages/Store.vue (hunk 4 above)
Comment (talwinder50) [reply cmd/wallet-web/src/pages/Store.vue]: updated

**Review by birtony — APPROVED** [review]
