### PR TITLE
fix: [oidc4vci] web wallet view - fix OIDC router

### LINKED ISSUE #1619: [oidc4vci] web wallet view - fix OIDC router
Currently OIDC landing `/oidc` checks for query parameters to decide oidc share vs save flow.

Expected: 

- 'oidc/share' path should initiate oidc share flow, where wallet is OIDC identity provider.
- 'oidc/initiate' path should initiate oidc save flow, where wallet is OIDC client
- 'oidc/save' should be callback for authorize request flow
- Parent component of router (eg: OIDC.vue) should only have common layout related features

### PR DESCRIPTION
**Pull request by talwinder50**
closes #1619

Signed-off-by: talwinder50 <talwinderkaur50@gmail.com>

https://user-images.githubusercontent.com/7862595/170584829-c90c8a83-9a27-4b6b-b1b0-21453270a236.mp4

### CODE REVIEW

File: cmd/wallet-web/src/router/routes.js [hunk 1]
```diff
@@ -77,27 +77,22 @@ export default [
...
+        path: 'oidc/share',
+        name: 'oidcShare',
+        component: load('layouts/OIDCShareLayout'),
+        meta: { requiresAuth: true, signin: true, disableCHAPI: true, isNavbarHidden: true },
+      },
+      {
+        path: 'oidc/save',
+        name: 'oidcSave',
+        component: load('layouts/OIDCSaveLayout'),
+        meta: { requiresAuth: true, signin: true, disableCHAPI: true, isNavbarHidden: true },
```
Comment (birtony) [inline cmd/wallet-web/src/router/routes.js:95]: This does not look right. Since `oidc/` is the base for all three of them, it would make more sense to me to have one parent `oidc` route with 3 children. Similar to how `DashboardLayout` has a number of children

Comment (talwinder50) [reply cmd/wallet-web/src/router/routes.js]: updated

**Review by HeidiHan0000 — APPROVED** [review]

File: cmd/wallet-web/src/router/routes.js (hunk 1 above)
Comment (sudeshrshetty) [reply cmd/wallet-web/src/router/routes.js]: @birtony I remember last time you suggested to have them separated since they behave completely different when accessed, and there is no default view for `/oidc`. Can we discuss this?

**Review by sudeshrshetty — CHANGES_REQUESTED** [review]
should decide on approach of using different routers vs same with parent-child

**Review by sudeshrshetty — APPROVED** [review]
