### PR TITLE
fix: fixed navigation guard issue

### LINKED ISSUE #1753: Agent opts are undefined in gnap flow navigation guards

### PR DESCRIPTION
**Pull request by birtony**
Fixes #1753

Signed-off-by: Anton Biriukov <anton.biriukov@securekey.com>

### CODE REVIEW

File: cmd/wallet-web/src/components/SkeletonLoader/CredentialPreviewSkeletonComponent.vue [hunk 1]
```diff
@@ -5,7 +5,6 @@
 -->
 
 <script setup>
-import { defineProps } from 'vue';
```
Comment (birtony) [inline cmd/wallet-web/src/components/SkeletonLoader/CredentialPreviewSkeletonComponent.vue:8]: `defineProps` no longer need to be imported since they are defined as compiler macros and are available inside the `setup` script by default https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits
cc @HeidiHan0000

Comment (HeidiHan0000) [reply cmd/wallet-web/src/components/SkeletonLoader/CredentialPreviewSkeletonComponent.vue:8]: Thanks for letting me know, will keep in mind next time!

**Review by talwinder50 — APPROVED** [review]

**Review by Moopli — APPROVED** [review]

**Review by fqutishat — APPROVED** [review]
