### PR TITLE
fix: use title from credentialmanifest

### LINKED ISSUE #1824: Credential display uses fields from metadata instead of resolved manifest
When a VC that is missing the name property is saved into wallet, the wallet shows a credential with an empty title.
Screen Shot 2022-07-26 at 3 11 51 PM

In the pages related to saving (ex `WACIIssuePage`), the title is shown. This is because `WACIIssuePage` uses the credential name from the credential manifest (returned from `resolveManifest`) while the `CredentialsPage` uses the credential name from `getCredentialMetadata`

### PR DESCRIPTION
**Pull request by HeidiHan0000**
Closes #1824 
What's changed:
If the 'credential name' property in a vc is empty, use the title from the credential manifest (returned from resolveManifest) instead - this is in [CredentialDetailsPage](https://github.com/trustbloc/wallet/compare/main...HeidiHan0000:wallet:issue-1824?expand=1#diff-936eaa2bc7316c5c0a24b5d06f8fc304526a63a985db8a470a46a7a8d11baa0dR197), [CredentialsPage](https://github.com/trustbloc/wallet/compare/main...HeidiHan0000:wallet:issue-1824?expand=1#diff-31f5afb2683cbf248197fb5dcf47321325ee209c4ab8cb27f5762017253c1905R236), [OIDCSharePage](https://github.com/trustbloc/wallet/compare/main...HeidiHan0000:wallet:issue-1824?expand=1#diff-c2fd5c10cf3198ca1ce1bd4a62ba8e5442d9bb5470fd409d31b42bc02b231cdcR230), and [WACISharePage](https://github.com/trustbloc/wallet/compare/main...HeidiHan0000:wallet:issue-1824?expand=1#diff-6b515f1481bd545edb0b9b2d62035d45010f689d1772224abf184f4c7e3185e4R238) (the rest of the changes are from linting). 

Name is an optional property in vc (id and issuanceDate are required fields), so if it is empty, it should get its value from credential manifest. (If it isn't empty, continue using the name from the vc because user may have changed the name of the vc). The case where the credential manifest is missing the title (equivalent of name property) and needs to get data from [credential-output-descriptors.json](https://github.com/trustbloc/wallet/blob/main/cmd/wallet-web/src/config/credential-output-descriptors.json#L2) like mentioned on the issue will be covered in #1832 

Signed-off-by: heidihan0000 <daeun.han@avast.com>

### CODE REVIEW

**Review by rolsonquadras — APPROVED** [review]

File: cmd/wallet-web/src/pages/CredentialDetailsPage.vue [hunk 1]
```diff
@@ -190,18 +190,24 @@ export default {
...
       this.credentialManager = new CredentialManager({ agent: this.getAgentInstance(), user });
       try {
-        const { id, name, issuanceDate, resolved } =
+        let { id, name, issuanceDate, resolved } =
           await this.credentialManager.getCredentialMetadata(
             this.token,
             decode(this.$route.params.id)
           );
+        if (!name) name = resolved[0].title;
         this.credential = { id, issuanceDate, name, ...resolved[0] };
```
Comment (birtony) [inline cmd/wallet-web/src/pages/CredentialDetailsPage.vue:199]: Maybe we could do this instead:
```suggestion
        this.credential = { id, issuanceDate, name || resolved[0].title, ...resolved[0] };
```

File: cmd/wallet-web/src/pages/CredentialsPage.vue [hunk 2]
```diff
@@ -233,7 +233,7 @@ export default {
         });
         return metadataList.map((credential) => ({
           id: encode(credential.id),
-          name: credential.name,
+          name: credential.name ? credential.name : credential.resolved[0].title,
```
Comment (birtony) [inline cmd/wallet-web/src/pages/CredentialsPage.vue:236]:
```suggestion
          name: credential.name || credential.resolved[0].title,
```

**Review by birtony — COMMENTED** [review]
Looks good, but maybe we could avoid using `let` instead of `const` and follow something like this

**Review by birtony — APPROVED** [review]
Nice
